"""Invariant: no retired Task Agent name survives the task 044 sweep.

The 038 precedent (`test_rename_038.py` is the tool's unit test; this file is
the *result* test): grep the shipped tree for every word the rename retired and
fail on anything the rules did not explicitly keep. The kept list is
`docs/tasks/044-scoping-shell-baseline/rename-rules.md` § "Never mapped" plus
the thirteen hash-pinned prompt modules, which the sweep excludes whole so that
every pinned hash but the moved one stays byte-identical (rubric 13).
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterator
from pathlib import Path

import httpx
import pytest
from fastapi.testclient import TestClient
from sqlalchemy.engine import Engine

from policy_atlas.runtime.task_agent_prompt import PLANNER_PROMPT_VERSION
from tests.api.resource_support import api_client, create_task

_REPO = Path(__file__).resolve().parents[3]

# Every retired name the shipped tree must no longer carry.
_RETIRED: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("planning_transcript", re.compile(r"planning_transcript")),
    ("/planning-turns", re.compile(r"planning-turns")),
    ("PlanningTurn", re.compile(r"PlanningTurn")),
    ("PlannerBackend", re.compile(r"PlannerBackend")),
    ("planner_prompt", re.compile(r"planner_prompt")),
    ("POLICY_ATLAS_PLANNER_MODEL", re.compile(r"POLICY_ATLAS_PLANNER_MODEL")),
)

# Kept by rules-doc decision: a hit overlapping one of these is not a failure.
_KEPT: tuple[re.Pattern[str], ...] = (
    re.compile(r"eb_iof_base_v1"),
    re.compile(r"eb_icf_base_v1"),
    re.compile(r"evidence_base_coverage"),
    # Stored `country_group.authorship` value inside plan payloads.
    re.compile(r"planner-proposed"),
    re.compile(r"planner_v\d+"),
    # The kept wire role literal, in every shape: `role` on the same line.
    re.compile(r"\brole\b[^\n]{0,80}?[\"']planner[\"']"),
    re.compile(r"[\"']planner[\"'][^\n]{0,80}?\brole\b"),
    # `infra/DEPLOYMENT.md` names the old variable once, in the note that says
    # the rename happened and that no fallback read was added.
    re.compile(r"`POLICY_ATLAS_PLANNER_MODEL` became"),
)

_CODE_ROOTS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("backend/src", (".py",)),
    ("frontend/src", (".ts", ".tsx", ".md")),
    ("frontend/e2e", (".ts",)),
)

_DOCS_FILES: tuple[str, ...] = (
    "infra/DEPLOYMENT.md",
    "docs/specs/system/web-api.md",
)


def _pinned_prompt_modules() -> frozenset[str]:
    """The hash-pinned prompt modules, which the sweep excludes whole.

    Their interiors are the lead's (AGENTS.md) and every hash but the moved
    one must not change, so `runtime/agent_prompt.py`'s docstring mention of
    `planner_prompt.py` is stale on purpose — flagged in `verification.md`,
    not swept.
    """
    pins = json.loads((_REPO / "scripts" / "prompt_hashes.json").read_text(encoding="utf-8"))
    return frozenset(str(key) for key in pins)


def _code_files() -> Iterator[str]:
    excluded = _pinned_prompt_modules()
    for base, suffixes in _CODE_ROOTS:
        for path in sorted((_REPO / base).rglob("*")):
            if not path.is_file() or path.suffix not in suffixes:
                continue
            rel = path.relative_to(_REPO).as_posix()
            # Generated by `make openapi-sync`, never hand-edited.
            if rel.startswith("frontend/src/api/gen/") or rel in excluded:
                continue
            yield rel


def _hits(rel: str) -> list[str]:
    """Every retired-name occurrence in one file that no kept rule covers."""
    text = (_REPO / rel).read_text(encoding="utf-8")
    kept = [span for pattern in _KEPT for span in pattern.finditer(text)]
    found: list[str] = []
    for label, pattern in _RETIRED:
        for match in pattern.finditer(text):
            if any(k.start() < match.end() and match.start() < k.end() for k in kept):
                continue
            line = text.count("\n", 0, match.start()) + 1
            found.append(f"{rel}:{line}: {label}")
    return found


def test_no_retired_task_agent_name_survives_in_the_code() -> None:
    """`backend/src`, `frontend/src` and `frontend/e2e` carry no retired name."""
    found = [hit for rel in _code_files() for hit in _hits(rel)]
    assert found == [], "retired names survive:\n" + "\n".join(found)


@pytest.mark.parametrize("rel", _DOCS_FILES)
def test_no_retired_task_agent_name_survives_in_the_docs(rel: str) -> None:
    """The two deployment/API documents carry no retired name."""
    found = _hits(rel)
    assert found == [], "retired names survive:\n" + "\n".join(found)


def test_the_schema_module_carries_only_the_new_names() -> None:
    """`core/schema.py` names the table, the column and every constraint anew."""
    text = (_REPO / "backend/src/policy_atlas/core/schema.py").read_text(encoding="utf-8")
    for retired in (
        "planning_transcript",
        "planner_state",
        "uq_ptr_",
        "ck_ptr_",
        "'planner'",
        "ck_conversation_planning_never_archived",
        "uq_conversation_one_active_planning",
        "kind IN ('planning'",
    ):
        assert retired not in text, f"`core/schema.py` still carries {retired!r}"
    for expected in (
        '"task_agent_transcript"',
        '"task_agent_state"',
        "uq_tat_task_client_turn",
        "ck_tat_suggestions_array",
        "ck_conversation_task_agent_never_archived",
        "uq_conversation_one_active_task_agent",
        "kind IN ('task_agent', 'chat')",
    ):
        assert expected in text, f"`core/schema.py` is missing {expected!r}"


def test_the_pinned_prompt_version_string_is_unchanged() -> None:
    """R1: the stored provenance value moves with nothing (rules § Never mapped)."""
    assert PLANNER_PROMPT_VERSION == "planner_v11"


def test_the_old_route_is_gone_and_the_new_one_answers(engine: Engine, tmp_path: Path) -> None:
    """No redirect and no alias: the retired path 404s (038 rule, contract D2).

    Takes `engine` only for its migration side effect: this module is otherwise
    file-only, so nothing else here brings the schema up.
    """
    del engine
    with api_client(tmp_path) as (client, owner, _other):
        task_id = create_task(client, owner)
        assert _post_turn(client, owner, task_id, "planning-turns").status_code == 404
        assert _post_turn(client, owner, task_id, "task-agent-turns").status_code != 404


def _post_turn(
    client: TestClient, headers: dict[str, str], task_id: str, segment: str
) -> httpx.Response:
    response: httpx.Response = client.post(
        f"/api/v1/tasks/{task_id}/{segment}",
        headers=headers,
        json={"client_turn_id": "00000000-0000-4000-8000-000000000001", "message": "hello"},
    )
    return response
