"""initial

Revision ID: 68afc1c2def1
Revises: 
Create Date: 2026-06-23 16:36:28.032319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68afc1c2def1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('artefact',
    sa.Column('artefact_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('artefact_id')
    )
    op.create_table('runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('run_id'),
    sa.UniqueConstraint('run_id', 'project_id', name='uq_runs_run_project')
    )
    op.create_table('block',
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('artefact_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artefact_id'], ['artefact.artefact_id'], ),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('event_log',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['run_id', 'project_id'], ['runs.run_id', 'runs.project_id'], name='fk_event_log_run_project'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('project_id', 'sequence', name='uq_event_log_project_sequence')
    )
    op.create_table('addressable_unit',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('unit_type', sa.Text(), nullable=False),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.block_id'], ),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('block_id', 'unit_id', name='uq_addressable_unit_block_unit')
    )
    op.create_table('annotation',
    sa.Column('annotation_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('annotation_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_id', 'unit_id'], ['addressable_unit.block_id', 'addressable_unit.unit_id'], name='fk_annotation_block_unit'),
    sa.PrimaryKeyConstraint('annotation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation')
    op.drop_table('addressable_unit')
    op.drop_table('event_log')
    op.drop_table('block')
    op.drop_table('runs')
    op.drop_table('artefact')
    op.drop_table('project')
    # ### end Alembic commands ###
