"""Emit the rename manifest for task 038 from ``core/schema.py``.

Deterministic: every table, column, named constraint, index and view whose
name carries one of the old vocabulary tokens, with its target name. The
migration and the round-trip test are written from this output, never typed.

Usage: ``python3 scripts/schema_manifest.py > docs/tasks/038-vocabulary-alignment/schema-manifest.md``
"""

from __future__ import annotations

import re
from pathlib import Path

SCHEMA = Path(__file__).resolve().parents[1] / "backend/src/policy_atlas/core/schema.py"

# Ordered: longest / most specific first so ``project_source_snapshot`` is
# renamed before the bare ``project`` token is, and ``portfolio`` is renamed
# only after every ``project`` has become ``task`` (the two-step order).
STEP1 = [
    ("project_source_snapshot", "task_source_snapshot"),
    ("uq_pss_", "uq_tss_"),
    ("_pss_", "_tss_"),
    ("orchestration_plan", "plan"),
    ("_oplan_", "_plan_"),
    ("project", "task"),
]
STEP2 = [("portfolio", "project")]
TOKEN = re.compile(r"project|portfolio|oplan|orchestration_plan|evidence_base|capr_capability")


def rename(name: str) -> str:
    for old, new in STEP1 + STEP2:
        name = name.replace(old, new)
    return name


def main() -> None:
    src = SCHEMA.read_text()
    tables = re.findall(r'^\w+ = Table\(\s*\n\s*"(\w+)"', src, re.M)
    views = re.findall(r'"(finding_reference_union)"', src)[:1]
    named = sorted(set(re.findall(r'name="([^"]+)"', src)))
    print("# Schema rename manifest (task 038)\n")
    print("Generated by `scripts/schema_manifest.py` from `core/schema.py`. Do not edit.\n")
    print("Order: step 1 renames every `project*`/`orchestration_plan` object; step 2 renames")
    print("`portfolio*`. The downgrade runs the same table in reverse order.\n")
    print("## Tables\n\n| Today | After |\n|---|---|")
    for t in tables:
        if TOKEN.search(t):
            print(f"| `{t}` | `{rename(t)}` |")
    print("\n## Columns\n\n| Table (today) | Column today | Column after |\n|---|---|---|")
    for t in tables:
        body = src[src.index(f'"{t}",') :]
        body = body[: body.find("\n)\n")]
        for col in re.findall(r'Column\(\s*"(\w+)"', body):
            if TOKEN.search(col):
                print(f"| `{t}` | `{col}` | `{rename(col)}` |")
    print("\n## Named constraints and indexes\n\n| Today | After |\n|---|---|")
    for n in named:
        if TOKEN.search(n):
            print(f"| `{n}` | `{rename(n)}` |")
    print("\n## Views\n")
    for v in views:
        print(f"- `{v}` — recreated with `task_id` in place of `project_id`.")
    print("\n## Stored values\n")
    print("- `capability_run.capability`: `'evidence_base'` → `'evidence_search'` (UPDATE + `ck_capr_capability` swap).")
    print("- `event_log.event_type`: `project.renamed|archived|shared_publicly|unshared` → `task.*` on new writes; readers accept both; downgrade rewrites `task.*` → `project.*`.")
    print("- JSONB `decided_by`/`authored_by`: `orchestrator` → `agent` on new writes; downgrade rewrites back.")
    print("- JSONB steer-point id: `evidence_base_coverage` → `evidence_search_coverage` on new writes; downgrade rewrites back.")


if __name__ == "__main__":
    main()
