"""Emit the rename manifest for task 038 from the SQLAlchemy metadata.

Deterministic and complete: every table, column, primary key, foreign key,
CHECK, UNIQUE and index (named or positional, explicit or auto-named by
PostgreSQL's ``<table>_pkey`` / ``<table>_<col>_fkey`` convention) whose
name carries one of the old vocabulary tokens, with its target name. The
migration and the round-trip test are written from this output, never typed.

Usage (from the repo root)::

    uv run --project backend python scripts/schema_manifest.py \
        > docs/tasks/038-vocabulary-alignment/schema-manifest.md
"""

from __future__ import annotations

import re

from sqlalchemy import CheckConstraint, ForeignKeyConstraint, PrimaryKeyConstraint, UniqueConstraint

from policy_atlas.core import schema

# Ordered: compound tokens before their bare prefix; ``portfolio`` last so it
# runs only after every ``project`` has become ``task`` (the two-step order).
STEP1 = [
    ("project_source_snapshot", "task_source_snapshot"),
    ("uq_pss", "uq_tss"),
    ("_pss_", "_tss_"),
    ("ck_pss", "ck_tss"),
    ("fk_pss", "fk_tss"),
    ("orchestration_plan", "plan"),
    ("_oplan_", "_plan_"),
    ("project", "task"),
]
STEP2 = [("portfolio", "project")]
TOKEN = re.compile(r"project|portfolio|pss|oplan|orchestration_plan|evidence_base|capr_capability")


def rename(name: str) -> str:
    for old, new in STEP1 + STEP2:
        name = name.replace(old, new)
    return name


def _row(kind: str, table: str, name: str) -> str:
    return f"| {kind} | `{table}` | `{name}` | `{rename(name)}` |"


def main() -> None:
    md = schema.metadata
    tables = sorted(md.tables.values(), key=lambda t: t.name)
    out: list[str] = []
    out.append("# Schema rename manifest (task 038)\n")
    out.append("Generated by `scripts/schema_manifest.py` from `policy_atlas.core.schema.metadata`. Do not edit.\n")
    out.append("Step 1 renames every `project*`, `*pss*` and `orchestration_plan` object; step 2 renames")
    out.append("`portfolio*`. The downgrade runs the same rows in reverse order. Auto-named objects follow")
    out.append("PostgreSQL's convention (`<table>_pkey`, `<table>_<column>_fkey`); the migration renames them")
    out.append("by those names and the round-trip test asserts the catalog matches this file.\n")

    out.append("## Tables\n\n| Today | After |\n|---|---|")
    for t in tables:
        if TOKEN.search(t.name):
            out.append(f"| `{t.name}` | `{rename(t.name)}` |")

    out.append("\n## Columns\n\n| Table (today) | Column today | Column after |\n|---|---|---|")
    for t in tables:
        for c in t.columns:
            if TOKEN.search(c.name):
                out.append(f"| `{t.name}` | `{c.name}` | `{rename(c.name)}` |")

    out.append("\n## Constraints and indexes\n\n| Kind | Table (today) | Name today | Name after |\n|---|---|---|---|")
    for t in tables:
        for con in sorted(t.constraints, key=lambda c: (type(c).__name__, c.name or "")):
            if isinstance(con, PrimaryKeyConstraint):
                name = con.name or f"{t.name}_pkey"
                kind = "PK"
            elif isinstance(con, ForeignKeyConstraint):
                cols = "_".join(col.name for col in con.columns)
                name = con.name or f"{t.name}_{cols}_fkey"
                kind = "FK"
            elif isinstance(con, UniqueConstraint):
                name = con.name or f"{t.name}_{'_'.join(col.name for col in con.columns)}_key"
                kind = "UNIQUE"
            elif isinstance(con, CheckConstraint):
                name = con.name or "(unnamed CHECK — name it before renaming)"
                kind = "CHECK"
            else:
                continue
            if TOKEN.search(name) or TOKEN.search(t.name):
                out.append(_row(kind, t.name, name))
        for ix in sorted(t.indexes, key=lambda i: i.name or ""):
            if ix.name and (TOKEN.search(ix.name) or TOKEN.search(t.name)):
                out.append(_row("INDEX", t.name, ix.name))

    out.append("\n## Views\n")
    out.append("- `finding_reference_union` — dropped and recreated with `task_id` in place of `project_id` (its definition lives in `schema.py`).")

    out.append("\n## Stored values (five reversible updates)\n")
    out.append("1. `capability_run.capability`: `'evidence_base'` → `'evidence_search'`; `ck_capr_capability` dropped and recreated.")
    out.append("2. `event_log.event_type`: `project.renamed|archived|shared_publicly|unshared` → `task.*` on new writes; readers accept both; downgrade rewrites `task.*` → `project.*`.")
    out.append("3. `event_log.payload` JSONB `decided_by` / `authored_by`: `orchestrator` → `agent` on new writes; downgrade rewrites back.")
    out.append("4. `orchestration_plan.payload` (→ `plan.payload`) JSONB steer-point ids: `evidence_base_coverage` → `evidence_search_coverage` on new writes; downgrade rewrites back.")
    out.append("5. `event_log.payload` JSONB pause records (`checkin_read.py`) steer-point id: same as 4; downgrade rewrites back.")
    print("\n".join(out))


if __name__ == "__main__":
    main()
