"""The `/api/v1` Pydantic contract package.

Canonical source of truth for `/api/v1` shapes (spec
`docs/specs/system/web-api.md`) — OpenAPI is generated from these models,
the TypeScript client from the OpenAPI document. This package is
dependency-free beyond `pydantic`/`uuid`/`datetime`/`typing`: it never
imports `policy_atlas.runtime` or `policy_atlas.evidence_base`.
"""

from __future__ import annotations

from .check_ins import (
    AbortResponse,
    CheckInBoundary,
    CheckInOption,
    CheckInOut,
    CheckInResponse,
    CheckInStatus,
    CheckInTrigger,
    FreeTextCompileOut,
    FreeTextConfirmResponse,
    FreeTextResponse,
    OptionResponse,
)
from .common import (
    PAGE_SIZE_DEFAULT,
    PAGE_SIZE_MAX,
    ErrorBody,
    ErrorEnvelope,
    Page,
    PageMeta,
)
from .planning import (
    AnalysisDepth,
    BackendScope,
    CountryGroupAuthorship,
    CountryGroupDraft,
    DiscretionaryComponent,
    ExtractProfile,
    GroupingFacet,
    PlanDraft,
    PlanningTranscriptTurnOut,
    PlanningTurnCreate,
    PlanningTurnOut,
    PlanOut,
    PlanStep,
    ScopeConstraintsDraft,
    SearchEffort,
    SteeringMode,
)
from .projects import (
    PROJECT_NAME_MAX,
    LatestRun,
    ProjectCreate,
    ProjectOut,
    ProjectStatus,
    ProjectUpdate,
)
from .read_models import (
    ArtefactOut,
    BlockOut,
    ChunkContextOut,
    CitationOut,
    ClaimOut,
    ClaimType,
    CoverageOut,
    CoverageSnapshotOut,
    DecisionOut,
    EvidenceItemOut,
    EvidenceOrigin,
    EvidenceStatus,
    FacetGroupsOut,
    FindingOut,
    FindingRelevance,
    FunnelOut,
    GroupOut,
    GroupsOut,
    LandscapeOut,
    ReferenceOut,
    SectionOut,
    SectionRole,
    ThemeOut,
)
from .runs import RunCreate, RunOut, RunStatus
from .sse import (
    STAGE_KEYS,
    CheckinPendingFrame,
    CheckinResolvedFrame,
    DecidedBy,
    PlanUpdatedFrame,
    ProjectUpdatedFrame,
    RunStatusFrame,
    SseFrame,
    StageCompletedFrame,
    StageFailedFrame,
    StageKey,
    StageStartedFrame,
    TickFrame,
)

__all__ = [
    "PAGE_SIZE_DEFAULT",
    "PAGE_SIZE_MAX",
    "PROJECT_NAME_MAX",
    "STAGE_KEYS",
    "AbortResponse",
    "AnalysisDepth",
    "ArtefactOut",
    "BackendScope",
    "BlockOut",
    "CheckInBoundary",
    "CheckInOption",
    "CheckInOut",
    "CheckInResponse",
    "CheckInStatus",
    "CheckInTrigger",
    "CheckinPendingFrame",
    "CheckinResolvedFrame",
    "ChunkContextOut",
    "CitationOut",
    "ClaimOut",
    "ClaimType",
    "CountryGroupAuthorship",
    "CountryGroupDraft",
    "CoverageOut",
    "CoverageSnapshotOut",
    "DecidedBy",
    "DecisionOut",
    "DiscretionaryComponent",
    "ErrorBody",
    "ErrorEnvelope",
    "EvidenceItemOut",
    "EvidenceOrigin",
    "EvidenceStatus",
    "ExtractProfile",
    "FacetGroupsOut",
    "FindingOut",
    "FindingRelevance",
    "FreeTextCompileOut",
    "FreeTextConfirmResponse",
    "FreeTextResponse",
    "FunnelOut",
    "GroupOut",
    "GroupsOut",
    "GroupingFacet",
    "LandscapeOut",
    "LatestRun",
    "OptionResponse",
    "Page",
    "PageMeta",
    "PlanDraft",
    "PlanOut",
    "PlanStep",
    "PlanUpdatedFrame",
    "PlanningTranscriptTurnOut",
    "PlanningTurnCreate",
    "PlanningTurnOut",
    "ProjectCreate",
    "ProjectOut",
    "ProjectStatus",
    "ProjectUpdate",
    "ProjectUpdatedFrame",
    "ReferenceOut",
    "RunCreate",
    "RunOut",
    "RunStatus",
    "RunStatusFrame",
    "ScopeConstraintsDraft",
    "SearchEffort",
    "SectionOut",
    "SectionRole",
    "SseFrame",
    "StageCompletedFrame",
    "StageFailedFrame",
    "StageKey",
    "StageStartedFrame",
    "SteeringMode",
    "ThemeOut",
    "TickFrame",
]
